export type SyntaxEntry = {
  id: string;
  label: string;
  category: string;
  description: string;
  source: string;
  notes?: string[];
};

export const syntaxEntries: SyntaxEntry[] = [
  {
    id: 'paragraph',
    label: '段落、换行与转义',
    category: '基础排版',
    description: '用空行分隔段落，使用行末反斜杠强制换行。',
    source: '第一段文字。\n\n第二段第一行。\\\n第二段第二行。\n\n\\*这里的星号是文字\\*',
    notes: ['普通回车不一定产生换行；行末两个空格也可强制换行。需要原样显示 Markdown 标记时，在标记前加反斜杠。'],
  },
  {
    id: 'footnote',
    label: '脚注',
    category: '基础排版',
    description: '给正文添加补充解释，并在文末集中显示。',
    source: '这里有一条补充说明[^note]。\n\n[^note]: 这是脚注的内容。',
    notes: ['引用与定义使用相同标识；每条脚注的标识应唯一。'],
  },
  {
    id: 'heading',
    label: '标题',
    category: '基础排版',
    description: '用标题组织文章层级，预览中的目录会随标题更新。',
    source: '## 小节标题\n\n在这里开始写作。',
    notes: ['# 到 ###### 对应一级到六级；井号后留一个空格。文章名称在文章属性中填写，正文通常从二级标题开始。'],
  },
  {
    id: 'bold',
    label: '粗体',
    category: '基础排版',
    description: '突出段落中的关键字句。',
    source: '**重点文字**',
    notes: ['标记紧贴文字，两侧不要添加空格。'],
  },
  {
    id: 'italic',
    label: '斜体',
    category: '基础排版',
    description: '用较轻的强调区分术语、语气或作品名称。',
    source: '*轻声强调*',
    notes: ['文字两侧各用一个星号，标记紧贴文字；三个星号（***文字***）同时使用粗体与斜体。实际倾斜效果取决于预览字体。'],
  },
  {
    id: 'strike',
    label: '删除线',
    category: '基础排版',
    description: '保留被修订的文字，展示变化。',
    source: '~~旧的说法~~ 新的说明',
  },
  {
    id: 'quote',
    label: '引用',
    category: '基础排版',
    description: '引用文字支持段落、嵌套与其他 Markdown。',
    source: '> 引用的文字。\n>\n> ——出处',
    notes: ['每行以 > 开头；嵌套引用使用 >>。'],
  },
  {
    id: 'list',
    label: '列表',
    category: '基础排版',
    description: '用无序列表罗列内容，用有序列表表达步骤。',
    source: '- 第一项\n- 第二项\n  - 子项目\n\n1. 第一步\n2. 第二步',
    notes: ['子列表需要缩进，并与父项保持层级一致。'],
  },
  {
    id: 'task',
    label: '任务清单',
    category: '基础排版',
    description: '在源码中标记事项是否完成。',
    source: '- [ ] 尚未完成\n- [x] 已经完成',
    notes: ['[ ] 表示未完成，[x] 表示完成；预览复选框不代替源码编辑。'],
  },
  {
    id: 'table',
    label: '表格',
    category: '基础排版',
    description: '使用 GFM 表格比较并列数据。',
    source: '| 项目 | 说明 | 数量 |\n| :--- | :---: | ---: |\n| 示例 | 居中内容 | 1 |',
    notes: ['分隔行中的冒号控制左、居中或右对齐。单元格中的竖线写作 \\|。'],
  },
  {
    id: 'divider',
    label: '分隔线',
    category: '基础排版',
    description: '在两个内容段落之间插入分隔线。',
    source: '\n---\n',
    notes: ['与上下段落留出空行；文档开头的 --- 用于 frontmatter。'],
  },
  {
    id: 'link',
    label: '文字链接',
    category: '链接与媒体',
    description: '为文字添加链接，段落内的链接保持普通链接样式。',
    source: '[链接文字](https://example.com "链接说明")',
    notes: ['圆括号内依次填写 URL 和可选的双引号说明。'],
  },
  {
    id: 'image',
    label: '图片',
    category: '链接与媒体',
    description: '使用图片网址插入图片，并为图片填写替代文字。',
    source: '![描述图片内容](https://example.com/image.webp "图片说明")',
    notes: ['把示例网址替换成可访问的图片 URL。编辑器不上传本地图片，下载的 Markdown 也不包含图片文件。'],
  },
  {
    id: 'embed',
    label: '链接卡片与嵌入',
    category: '链接与媒体',
    description: '独占一行的网址可显示 OG 卡片；Twitter/X 与 CodePen 链接使用专用嵌入。',
    source: 'https://github.com/withastro/astro',
    notes: [
      '链接前后留出空行。OG 信息需要联网获取；外部网站或服务不可用时可能只显示链接。普通行内链接不会变成卡片。',
      'Twitter/X 使用推文详情链接，CodePen 使用作品的 /pen/ 链接。',
    ],
  },
  {
    id: 'audio',
    label: '音频',
    category: '链接与媒体',
    description: '用 Shoka 媒体标签生成音频播放器。',
    source: '{% media audio %}\n- name: 音频名称\n  url: https://example.com/audio.mp3\n{% endmedia %}',
    notes: ['列表使用 YAML 缩进；name 为曲名，url 为音频地址，也支持仓库播放器可解析的网易云歌曲链接。外部音源需可访问。'],
  },
  {
    id: 'playlist',
    label: '音频歌单',
    category: '链接与媒体',
    description: '将歌单链接组织成可切换的音频列表。',
    source: '{% media audio %}\n- title: 我的歌单\n  list:\n    - https://music.163.com/playlist?id=8676645748\n{% endmedia %}',
    notes: ['title 是列表标题，list 下逐行填写链接。网易云内容的可用性取决于配置的 Meting 服务与歌曲权限。'],
  },
  {
    id: 'video',
    label: '视频',
    category: '链接与媒体',
    description: '用媒体标签展示一个或多个视频。',
    source: '{% media video %}\n- name: 视频标题\n  url: https://example.com/video.mp4\n{% endmedia %}',
    notes: ['url 应为浏览器可播放的视频资源地址，而非普通视频网站页面；示例地址需要替换。'],
  },
  {
    id: 'friend',
    label: '友链卡片',
    category: '链接与媒体',
    description: '使用 YAML 列表展示网站、作者与简介。',
    source:
      '{% links %}\n- site: 网站名称\n  url: https://example.com\n  owner: 作者\n  desc: 一句话介绍\n  image: https://example.com/avatar.webp\n  color: "#ed788b"\n{% endlinks %}',
    notes: [
      'site、url 描述网站；owner、desc、image、color 补充作者、简介、头像和卡片颜色。多个网站分别以 - site 开始，保持相同缩进。',
    ],
  },
  {
    id: 'underline',
    label: '下划线与着重点',
    category: 'Shoka 文字',
    description: '使用普通、波浪下划线或着重点强调文字。',
    source: '++下划线++ ++波浪线++{.wavy} ++着重点++{.dot}',
    notes: ['可追加 .primary、.info、.success、.warning、.danger 改变颜色；属性紧贴结束标记。'],
  },
  {
    id: 'highlight',
    label: '高亮',
    category: 'Shoka 文字',
    description: '用标记笔效果突出一段文字。',
    source: '==值得记住的文字==',
    notes: ['两个等号包围文字，首尾不要留空格。'],
  },
  {
    id: 'subscript',
    label: '上下标',
    category: 'Shoka 文字',
    description: '书写化学式、指数或简短标注。',
    source: 'H~2~O 与 E = mc^2^',
    notes: ['单个 ~ 包围下标，^ 包围上标；复杂公式使用数学公式语法。'],
  },
  {
    id: 'color',
    label: '颜色与彩虹文字',
    category: 'Shoka 文字',
    description: '为文字添加主题颜色或彩虹效果。',
    source: '[粉色文字]{.pink} [蓝色文字]{.blue} [彩虹文字]{.rainbow}',
    notes: ['颜色支持 red、pink、orange、yellow、green、aqua、blue、purple、grey。仅添加类名不会创建新的自定义颜色。'],
  },
  {
    id: 'keyboard',
    label: '键盘按键',
    category: 'Shoka 文字',
    description: '让快捷键看起来像键盘上的按键。',
    source: '[Ctrl]{.kbd} + [S]{.kbd}',
  },
  {
    id: 'label',
    label: '文字标签',
    category: 'Shoka 文字',
    description: '为短文字加上标签背景。',
    source: '[提示]{.label .info} [完成]{.label .success}',
    notes: ['label 控制标签样式，搭配 default、primary、info、success、warning 或 danger。'],
  },
  {
    id: 'attrs',
    label: '元素属性',
    category: 'Shoka 文字',
    description: '将本站已有样式类或锚点 ID 应用到文字和前一个区块。',
    source: '[带锚点的文字]{.primary #example-anchor}\n\n这是一个段落。\n\n{.blue}',
    notes: [
      '.名称为类名，#名称为锚点 ID；独立的属性段落作用于前一个元素。类名需有对应样式，任意类名不保证有效；事件处理属性不会执行。',
    ],
  },
  {
    id: 'spoiler',
    label: '隐藏文字',
    category: 'Shoka 文字',
    description: '将剧透或答案暂时隐藏，点击后显示。',
    source: '!!点击查看的文字!!\n\n!!模糊文字!!{.blur}',
    notes: ['.blur 使用模糊效果。隐藏文字只是视觉遮挡，不提供内容加密。'],
  },
  {
    id: 'ruby',
    label: '注音',
    category: 'Shoka 文字',
    description: '在文字上方标注读音。',
    source: '{漢字^かんじ} {词语^=整词注音} {重点^*}',
    notes: ['花括号内，^ 左侧是正文，右侧是注音；^= 标记整词注音，^* 显示着重点。适合短词组。'],
  },
  {
    id: 'note',
    label: '提醒块',
    category: 'Shoka 区块',
    description: '用带色彩与图标的区块补充说明。',
    source: ':::info\n这里是一条补充说明，支持 **Markdown**。\n:::',
    notes: [
      '类型支持 default、primary、info、success、warning、danger；例如 :::info no-icon 可隐藏图标。结束的 ::: 独占一行。',
    ],
  },
  {
    id: 'collapse',
    label: '折叠块',
    category: 'Shoka 区块',
    description: '将较长补充内容收进可展开的标题下。',
    source: '+++primary 点击展开\n这里是详细内容。\n\n- 说明一\n- 说明二\n+++',
    notes: ['+++ 后依次写类型与标题；类型与提醒块相同。结束的 +++ 独占一行。'],
  },
  {
    id: 'tabs',
    label: '标签卡',
    category: 'Shoka 区块',
    description: '把多个相邻内容块组织成可切换的标签页。',
    source: ';;;example 第一页\n第一页内容。\n;;;\n\n;;;example 第二页\n第二页内容。\n;;;',
    notes: ['example 是组名，同组标签使用相同名称；另一组请换名称。组名后为空格和显示标题，每页用独立的 ;;; 结束。'],
  },
  {
    id: 'quiz',
    label: '单选与多选',
    category: '练习与加密',
    description: '将嵌套列表转换为可作答的选择题。',
    source: '- 哪一个是正确答案？{.quiz}\n  - 正确选项{.correct}\n  - 其他选项{.options}\n\n> 解析：这里说明答案。',
    notes: [
      '题干加 .quiz，多选另加 .multi；正确选项标记 .correct，其他选项标记 .options。多选可有多个正确选项。站点需要启用练习题交互。',
    ],
  },
  {
    id: 'truefalse',
    label: '判断题',
    category: '练习与加密',
    description: '没有子选项的题目可作为判断题。',
    source: '- 一加一等于二。{.quiz .true}\n\n> 解析：这是一道判断题。',
    notes: ['.true 表示正确答案为“对”；省略 .true 表示“错”。'],
  },
  {
    id: 'fill',
    label: '填空题',
    category: '练习与加密',
    description: '将答案放进空格标记，读者填写后查看结果。',
    source: '- 水的化学式是 [H2O]{.gap}。{.quiz .fill}\n\n> 解析：常见错误答案是 [HO2]{.mistake}。',
    notes: ['题干同时带 .quiz .fill；[答案]{.gap} 可以出现多次；.mistake 用于说明错误答案。'],
  },
  {
    id: 'encrypted',
    label: '加密区块',
    category: '练习与加密',
    description: '将正文的一部分设为需要密码解锁的区块。',
    source: ':::encrypted{password="demo"}\n输入密码后才能阅读这段内容。\n:::',
    notes: [
      'demo 是示例密码，请自行修改；区块内可以继续使用 Markdown。',
      '发布构建会加密输出。编辑器源码、浏览器草稿和导出的 Markdown 仍包含明文与密码，不能作为加密备份。',
    ],
  },
  {
    id: 'encryptedpost',
    label: '整篇文章加密',
    category: '练习与加密',
    description: '在文章开头的 YAML 属性中设置 password，为整篇正文加密。',
    source: 'password: "demo"',
    notes: [
      '这是 frontmatter 字段片段：复制到文档最开头已有的 --- 属性区内，或在文章属性中设置；不要作为正文插入。',
      '标题等文章元信息不属于加密正文。源码、浏览器草稿与下载文件仍含明文和密码。',
    ],
  },
  {
    id: 'code',
    label: '行内代码与代码块',
    category: '代码与图表',
    description: '短代码用反引号包围，多行代码用围栏并标明语言。',
    source: '`const answer = 42`\n\n```js\nconsole.log("你好，世界");\n```',
    notes: ['js 可替换为 ts、python、bash 等语言名；代码块内按原样显示，不解析其他 Markdown。'],
  },
  {
    id: 'codemeta',
    label: '代码标题与行标记',
    category: '代码与图表',
    description: '为代码块添加文件名、源码链接、重点行或终端提示符。',
    source:
      '```js title="hello.js" url="https://example.com" linkText="查看源码" mark:1,3\nconst greeting = "你好";\nconst name = "世界";\nconsole.log(greeting, name);\n```\n\n```bash command:("$":1-2)\npnpm install\npnpm dev\n```',
    notes: [
      'title 为标题；url 与 linkText 为外链及文字；mark:1,3-5 高亮第 1、3 至 5 行，行号从 1 开始。',
      'command:("$":1-2) 为指定行添加提示符；提示符不必写进实际代码。',
    ],
  },
  {
    id: 'formula',
    label: '数学公式',
    category: '代码与图表',
    description: '使用 KaTeX 渲染行内或独立公式。',
    source: '行内公式：$E = mc^2$\n\n$$\n\\int_0^1 x^2\\,dx = \\frac{1}{3}\n$$',
    notes: ['单个 $ 包围行内公式，双 $$ 包围独立公式。文章 math: false 会关闭公式样式；站点也需启用数学支持。'],
  },
  {
    id: 'mermaid',
    label: 'Mermaid 图表',
    category: '代码与图表',
    description: '用文字描述流程图、时序图等。',
    source: '```mermaid\nflowchart LR\n  A[写作] --> B[预览]\n  B --> C[导出]\n```',
    notes: ['围栏语言必须是 mermaid；第一行指定图表类型，例如 flowchart LR、sequenceDiagram 或 pie。图表只在需要显示时加载。'],
  },
  {
    id: 'infographic',
    label: '信息图',
    category: '代码与图表',
    description: '使用 AntV Infographic 的模板与数据描述信息图。',
    source:
      '```infographic\ninfographic list-grid-badge-card\ndata\n  title 写作流程\n  items\n    - label 写作\n      desc 记录想法\n    - label 预览\n      desc 检查排版\n    - label 导出\n      desc 保存文章\n```',
    notes: [
      '第一行的 infographic 后填写模板名；data 下用空格缩进 title、desc、items。它使用信息图专用语法，不是普通 YAML。',
      '条目可使用 label、desc、value、icon 等字段，具体取决于模板。',
    ],
  },
  {
    id: 'frontmatter',
    label: '文章属性',
    category: '文章设置',
    description: '文章最开头的 YAML 区域保存标题、日期、封面、分类等元信息。',
    source:
      '---\ntitle: 我的新文章\ndate: 2026-01-01\ndescription: 一句话介绍文章\ncover: https://example.com/cover.webp\ncategories:\n  - 笔记\ntags:\n  - 写作\ncatalog: true\nmath: true\nquiz: true\n---',
    notes: [
      '这是一份完整属性示例，应放在文档最开头，替换或合并已有属性，不要在正文中重复插入。',
      'cover 为封面 URL，catalog: false 时文章不计入分类页的分类树与篇数；link 可设置固定文章路径，draft: true 标记草稿，password 可设置整篇加密。复制与下载保留完整属性区。',
    ],
  },
];
